### ISSUE TITLE
[Question] DocumentFormat html

### ISSUE THREAD

**Issue by lcanavesio** [DevExpress-Examples/richedit-react-app#4]
HI DevExpress team!
I am testing the editor with the idea of ​​acquiring the license. I was wondering if you could even add support for html format.
Currently: 

export declare enum DocumentFormatApi {
    PlainText = 1,
    Rtf = 2,
    OpenXml = 4
}

**Comment by AdelorDM** [comment]
Hello,

Please excuse our late reply. We have no plans to support the Html format. We recommend using the HtmlEditor - https://js.devexpress.com/Demos/WidgetsGallery/Demo/HtmlEditor/Overview/jQuery/Light/

P.S. In the future, please use our Support Center - https://supportcenter.devexpress.com/
This is our main support channel.
